####################################################
# Oracle
####################################################
db.driver=oracle.jdbc.driver.OracleDriver

####################################################
# Nueva Arquitectura
####################################################
db.nva.url=jdbc:oracle:thin:@10.203.20.20:2022:ptve1
db.nva.user=Viefact
db.nva.password=n0tfAct2010

####################################################
# Bolsa Centralizada
####################################################
db.bctr.url=jdbc:oracle:thin:@10.191.148.160:1521/bctr
db.bctr.user=TAE_NOTIFICA
db.bctr.password=N0t!fs4L

####################################################
# Correo
####################################################
correo.usuario=info.comercio.movil
correo.password=info.comercio.movil
correo.remitente=info.comercio.movil@mail.telcel.com
correo.cem=comercio.electronico@mail.telcel.com

####################################################
# Firma
####################################################
firma.ext1=25813700
firma.ext2=3976
firma.ext3=25813976

####################################################
# Logs
####################################################
ruta.logs=./logs/
