####################################################
# Oracle
####################################################
db.driver=oracle.jdbc.driver.OracleDriver

####################################################
# Bolsa Centralizada
####################################################
db.bctr.url=jdbc:oracle:thin:@10.191.148.160:1521/bctr
db.bctr.user=TAE_NOTIFICA
db.bctr.password=N0t!fs4L

####################################################
# Correo
####################################################
correo.usuario=info.comercio.movil
correo.password=info.comercio.movil
correo.remitente=info.comercio.movil@mail.telcel.com
correo.cem=comercio.electronico@mail.telcel.com

####################################################
# Firma
####################################################
firma.telefono1=25813700
firma.extension=3976
firma.telefono2=25813976

####################################################
# Rutas
####################################################
ruta.logs=./logs/
ruta.contactos=./conf/ContactosFactNva.txt